FROM postgres:17-alpine

# PostgreSQL 17 Database Service
# Configuration template is included; schema initialization files will be mounted or copied to /docker-entrypoint-initdb.d/
COPY postgresql.conf /usr/local/share/postgresql/postgresql.conf.sample
